flowchart TD;
    Actions -->|40| Services;
    Actions -->|28| ApplicationPortsIn;
    Actions -->|53| Data;
    ApplicationPortsIn -->|15| Data;
    ApplicationPortsOut -->|14| Domain;
    Console -->|5| ApplicationPortsIn;
    Console -->|12| Framework;
    Data -->|6| DateTime;
    Data -->|13| Domain;
    Http -->|111| Framework;
    Http -->|23| ApplicationPortsIn;
    Http -->|1| Data;
    Infrastructure -->|49| Framework;
    Infrastructure -->|143| Domain;
    Infrastructure -->|29| Models;
    Infrastructure -->|29| ApplicationPortsOut;
    Infrastructure -->|16| DateTime;
    Models -->|6| Domain;
    Models -->|11| Framework;
    OpenApi -->|347| OpenApiAttributes;
    Providers -->|25| Infrastructure;
    Providers -->|5| Domain;
    Providers -->|23| ApplicationPortsOut;
    Providers -->|4| Framework;
    Services -->|35| ApplicationPortsOut;
    Services -->|38| Domain;
    Services -->|7| DateTime;
